### PR TITLE
Migrate to sound null safety

### PR DESCRIPTION
**Pull request by AyushBherwani1998**
## Description

- Migrate to sound null safety
- Bump up package version

### CODE REVIEW

**Comment by maheshmnj** [comment]
Awesome @AyushBherwani1998 looks good to me

**Comment by maheshmnj** [comment]
just to confirm inorder to use the null safe version of this package,the Flutter project should also support null safety (with the required dart sdk constraints  ```sdk: ">=2.12.0-0 <3.0.0"```)?

**Comment by maheshmnj** [comment]
Or its the other way around if a project wants to use the null safety feature it should you all the null safe versions of its dependencies.

**Comment by AyushBherwani1998** [comment]
To use the null safe version of the package, the Flutter project must satisfy the SDK constraint of `>=2.12.0-0 <3.0.0`.  Apart from that it should also satisfy transitive dependencies.  For instance if package `a-nullsafe` depends on package `b-nullsafe` and the project is using package `b`, it will raise issue of dependency.

**Comment by maheshmnj** [comment]
okay got it thank you so much.

**Pull request merged**
