### PR TITLE
Searchfield height

### PR DESCRIPTION
**Pull request by lilvinco**
https://github.com/maheshmnj/searchfield/issues/31

### CODE REVIEW

**Comment by maheshmnj** [comment]
Thanks for the PR can you also add the tests here https://github.com/maheshmnj/searchfield/blob/master/test/searchfield_test.dart?

**Comment by lilvinco** [comment]
Thanks @maheshmnj , I just added a test

**Comment by lilvinco** [comment]
@maheshmnj

**Comment by maheshmnj** [comment]
Hi @lilvinco, sorry for delay, give me some time, I will review this tomorrow and get back

**Comment by maheshmnj** [comment]
@lilvinco Can you resolve the conflicts and commit as per above changes so that we can get this landed?

**Comment by lilvinco** [comment]
@maheshmnj resolved

**Comment by maheshmnj** [comment]
@lilvinco Looks like the tests are failing there's some syntax error.

**Comment by maheshmnj** [comment]
@lilvinco I am closing this PR due to lack of inactivity. Incase you want to work on this PR again feel free to write back and I would be happy to reopen and review.

**Pull request closed without merging**
