### PR TITLE
adding autoValidateMode

### PR DESCRIPTION
**Pull request by dev-zayn**
adding autoValidateMode property to the TextFormField

### CODE REVIEW

**Comment by maheshmnj** [comment]
Thanks for the PR @dev-zayn, Can you also add a test? Let me know if you need any help. You can always look at the [existing tests](https://github.com/maheshmnj/searchfield/blob/master/test/searchfield_test.dart).

**Comment by dev-zayn** [comment]
@maheshmnj I added a test for it

**Comment by maheshmnj** [comment]
Hello   @dev-zayn, Wondering if you have had a chance to address the comments?

Thanks

**Comment by dev-zayn** [comment]
> Hello @dev-zayn, Wondering if you have had a chance to address the comments?

@maheshmnj Sorry for the late reply but what comments?

**Comment by maheshmnj** [comment]
@dev-zayn Please see my review comments above

**Comment by maheshmnj** [comment]
Closing as this property was added in v0.9.0

**Pull request closed without merging**
