### PR TITLE
(feat) added vertical padding to total height in _suggestion_builder

### PR DESCRIPTION
**Pull request by AndriiReverchuk**
Dear @maheshmnj,

I trust this email finds you well.

Firstly, I would like to extend my gratitude to you for the recent improvements you've made to the SearchField package. The addition of padding has greatly enhanced user interaction and brought a superior aesthetic quality to the feature. Your attention to detail and dedication to providing valuable contributions are both commendable and appreciated.

I wanted to bring to your attention that I have further refined the package by adding vertical padding to the total height in the suggestion_builder. I am attaching two videos that demonstrate the before and after effects of this enhancement for your reference.

### Before

https://github.com/maheshmnj/searchfield/assets/66751960/98b748af-9e8d-449f-ae87-b8692da2ce41

### After

https://github.com/maheshmnj/searchfield/assets/66751960/9940823c-8844-495a-99d9-bc30ec22f0ed

However, during my testing process, I noticed an issue related to animation jumping. While the overall functionality is not hindered, the jumping does have an adverse impact on user experience, given that fluid animation contributes significantly to a user-friendly interface.

Your expertise and insights would be of great help in resolving this issue. Could you please assist me in debugging this problem to ensure smoother animations? Your assistance in this matter would be greatly appreciated.

Looking forward to your positive response.

Best Regards,

Andrii

### CODE REVIEW

**Comment by maheshmnj** [comment]
Thanks for the PR @AndriiReverchuk I will review it soon.

**Comment by AndriiReverchuk** [comment]
@maheshmnj  Thank you for your feedback. I've added the tests as you requested. Apologies for the delay in adding them; I've been pressed for time. Let me know if there are any further changes needed.

**Comment by maheshmnj** [comment]
Hi Andrii,

Thank you for your thoughtful contribution and the kind words in your description. It's clear that you put significant time and effort into improving the Searchfield package, and I appreciate your dedication to enhancing the user experience.

I've reviewed the changes, and they look fantastic to me. I'll be merging this PR as it adds valuable enhancements to the package.

I understand the concern about animation jumping, and I'll make sure to look into it post-merge to ensure that we provide the best user experience possible. Your input is invaluable in this process.

Thanks again for your contribution, and I look forward to collaborating with you in the future.

Best,
Mahesh

**Comment by maheshmnj** [comment]
Released in [v0.8.7](https://pub.dev/packages/searchfield/changelog)

**Comment by AndriiReverchuk** [comment]
Dear @maheshmnj,

Thank you for your prompt response and positive feedback regarding my work on the Searchfield package. I'm glad that my efforts proved beneficial and contributed to the project's advancement.

I'm pleased that you addressed the animation issue. I'm confident that together we can find the best solution to this matter.

I look forward to further collaboration and am ready to assist in improving the package. If you have any additional questions or comments, please let me know.

Best regards,
Andrii Reverchuk.

**Pull request merged**
