### PR TITLE
Add option enabled

### PR DESCRIPTION
**Pull request by aglpy**
Add option enabled to enable or disable the widget as the traditional TextField can do.

### CODE REVIEW

**Comment by maheshmnj** [comment]
@aglpy Thanks for the PR I will review it soon.

**Comment by maheshmnj** [comment]
@aglpy Can you please add tests for it? Ping me if you need any help.

**Comment by aglpy** [comment]
@maheshmnj I added 2 tests based on previous tests, I am not used to make tests in flutter, I hope I made it well

**Comment by maheshmnj** [comment]
Thanks for the PR @aglpy!

**Comment by maheshmnj** [comment]
Published [v0.7.3](https://pub.dev/packages/searchfield/changelog)

**Pull request merged**
